name: Run Arxiv Script
on:
  schedule:
    - cron: '6 8 * * 1'
  workflow_dispatch: # This allows manual triggering
jobs:
  run-scripts:
    name: Run arxiv script
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      GH_KEY: ${{ secrets.GH_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      ANTHROPIC_APIKEY: ${{ secrets.ANTHROPIC_APIKEY }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup-ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'
      # Step 3: Install dependencies if any (uncomment if needed)
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Step 4: Run the Python script for 'cs'
      - name: Run arxiv script for cs
        run: python -c 'from arxiv_langchain import run; run("cs")' || echo fail

      # Repeat Step 4 for other categories
      - name: Run arxiv script for osf
        run: python -c 'from arxiv_langchain import run; run("osf")' || echo fail
      - name: Run arxiv script for q-fin
        run: python -c 'from arxiv_langchain import run; run("q-fin")' || echo fail
