name: Run Arxiv Script
on:
  schedule:
    - cron: '6 8 * * *' # This schedules the action to run every day at 8am UTC which is 4am EDT
  workflow_dispatch: # This allows manual triggering
jobs:
  run-scripts:
    name: Run arxiv script
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      GH_KEY: ${{ secrets.GH_KEY }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'
      # Step 3: Install dependencies if any (uncomment if needed)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the Python script for 'cs'
      - name: Run arxiv script for cs
        run: python -c 'from arxiv_langchain import run; run("cs")' || echo fail

      # Repeat Step 4 for other categories
      - name: Run arxiv script for q-bio
        run: python -c 'from arxiv_langchain import run; run("q-bio")' || echo fail

      - name: Run arxiv script for physics
        run: python -c 'from arxiv_langchain import run; run("physics")' || echo fail

      - name: Run arxiv script for q-fin
        run: python -c 'from arxiv_langchain import run; run("q-fin")' || echo fail
