name: Run Lions
on:
  schedule:
    - cron: '53 * * * *'
  workflow_dispatch: # This allows manual triggering
jobs:
  run-scripts:
    name: Run lions script
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      GH_KEY: ${{ secrets.GH_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      ANTHROPIC_APIKEY: ${{ secrets.ANTHROPIC_APIKEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup-ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'
          cache: 'pip' # caching pip dependencies
      # Step 3: Install dependencies if any (uncomment if needed)
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      # Step 4: Run the Python script
      - name: Run lions
        run: python -c 'import Lions'
